#application: wokantest
#version: ndb
runtime: python27
api_version: 1
threadsafe: false
automatic_scaling:
  max_instances: 1
builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /tinymce/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /(.*\.html)
  static_files: static/\1
  upload: static/.*\.html

- url: /assets
  static_dir: assets

- url: /admin/.*
  script: admin.main.application
  login: admin
  secure: always

- url: /comment/.*
  script: admin.main.application
  secure: always

- url: /_batch/.*
  script: batch.application
  login: admin

- url: /.*/edit
  script: admin.main.application
  login: admin

- url: /.*
  script: main.application
  secure: always
