#application: wokantest
#version: ndb
runtime: python39
automatic_scaling:
  max_instances: 1
#app_engine_apis: true

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /tinymce/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /(.*\.html)
  static_files: static/\1
  upload: static/.*\.html

- url: /assets
  static_dir: assets